name: Deploy Infrastructure

on:
  push:
    branches:
      - master

jobs:
  tf_fmt:
    name: Deploy Site
    runs-on: ubuntu-latest
    steps:
      - uses: kvrhdn/tfe-run@v1
        with:
          token: ${{ secrets.TF_API_TOKEN }}

          workspace: gh-actions-demo

          # The directory that is uploaded to Terraform Cloud/Enterprise, defaults
          # to the repository root. Respsects .terraformignore. Note: this is
          # prefixed to the "Terraform Working Directory" in the remote workspace
          # settings.
          directory: ./.deploy/terraform/static-site/

          message: |
            Run triggered using gh-actions-demo (commit: ${{ github.SHA }})
        id: gh-actions-demo
